name: Continuous Integration - .NET Core App

on:  
  pull_request:
    branches: [ main ]
env:
  CAMINHO_PROJETO_TESTES: ./src/Api.Service.Test
  
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407

    - name: Testes Automatizados com .Net Core 3.1 + XUnit
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

  build:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore    
